name: PyPI publish

on:
  workflow_run:
    workflows: ['Test on push']
    types:
      - completed

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pyfracgen
    permissions:
      id-token: write
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Load cached poetry
      id: cached-poetry
      uses: actions/cache@v3
      with:
        path: ~/.local
        key: poetry-0
    - name: Install Poetry
      if: steps.cached-poetry.outputs.cache-hit != 'true'
      uses: snok/install-poetry@v1
    - name: Check pyproject.toml
      run: poetry check --no-interaction
    - name: Build
      run: poetry build
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true
    


